### ISSUE TITLE
Bug: index.html absent.

### ISSUE THREAD

**Issue by 0wwafa** [mounta11n/plusplus-camall#13]
### What happened?

Click on NEW UI.
Then from the dropdown menu select old ui.
The url becomes /index.html (which does not exist) while it should become just /

### Name and Version

any

### Relevant log output

```shell
self explainatory. 404. error
```

**Comment by mounta11n** [comment]
Thanks for reporting. I have fixed that with [d9742fb](https://github.com/ggerganov/llama.cpp/pull/7633/commits/d9742fbf4efd80e6bb462bf487fc90df3eb3e24c)

I would love if you could confirm that it works now

**Comment by mounta11n** [comment]
I'm closing this issue because other users have confirmed it works now

**Comment by 0wwafa** [comment]
Yep. it does.
