### ISSUE TITLE
Bug: Unable to compil server : colorthemes.css.hpp missing

### ISSUE THREAD

**Issue by ali0une** [mounta11n/plusplus-camall#14]
### What happened?

Unable to compil server as file colorthemes.css.hpp missing

```
git clone https://github.com/mounta11n/plusplus-camall llama.cpp-Ui
cd llama.cpp-Ui/
git switch plusplus
export LLAMA_CUDA=1
make server -j$(nproc)
```

### Name and Version

```
git rev-parse --short HEAD
d0d4b0f0
```

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
examples/server/server.cpp:20:10: fatal error: colorthemes.css.hpp: Aucun fichier ou dossier de ce type
   20 | #include "colorthemes.css.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
```

**Comment by duynt575** [comment]
@ali0une Just do git clone https://github.com/mounta11n/plusplus-camall then compile, that's what I did. Don't add llama.cpp-Ui at the end.

**Comment by ali0une** [comment]
Many thanks @duynt575 !

To me that's still a bug, i have compiled several llama.cpp variant all cloned in a custom directory and this is the first that fails like this.

Tried to find where this plusplus-camall was hardcoded but did not find ... i guess i should try harder XD
For the time being i just mkdir llama.cpp-Ui and git clone here ^^

**Comment by mounta11n** [comment]
@ali0une I think this could be referred to missing mentions in the make file, which should be fixed now with [21138dd](https://github.com/ggerganov/llama.cpp/pull/7633/commits/21138dd2dac2cb023e9a82f48d225bc89c907bc0)

Could you please try it again with this commit and report back? Would be very helpful for me : )

**Comment by ali0une** [comment]
Many thanks @mounta11n works 100% now!

**Comment by mounta11n** [comment]
Okay perfect, glad to hear!
You're welcome:)
